apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-greeting-service-config-map
data:
  NUMBER_SERVICE_URL: {{ include "..fullname" . }}-number-service
  TIME_SERVICE_URL: {{ include "..fullname" . }}-time-service
  SECRET_SERVICE_URL: {{ include "..fullname" . }}-secret-service