apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..fullname" . }}-greeting-service
  labels:
    app.kubernetes.io/name: {{ include "..name" . }}-greeting-service
    helm.sh/chart: {{ include "..chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-greeting-service
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.greetingService.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "..name" . }}-greeting-service
      app.kubernetes.io/instance: {{ .Release.Name }}-greeting-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "..name" . }}-greeting-service
        app.kubernetes.io/instance: {{ .Release.Name }}-greeting-service
    spec:
      containers:
        - name: {{ .Chart.Name }}-greeting-service
          image: "{{ .Values.greetingService.image.repository }}:{{ .Values.greetingService.image.tag }}"
          imagePullPolicy: {{ .Values.greetingService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-greeting-service-config-map
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
