apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" . }}-secret-service
  labels:
    app.kubernetes.io/name: {{ include "..name" . }}-secret-service
    helm.sh/chart: {{ include "..chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-secret-service
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.secretService.service.type }}
  ports:
    - port: {{ .Values.secretService.service.port }}
      targetPort: {{ .Values.secretService.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "..name" . }}-secret-service
    app.kubernetes.io/instance: {{ .Release.Name }}-secret-service
