apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..fullname" . }}-time-service
  labels:
    app.kubernetes.io/name: {{ include "..name" . }}-time-service
    helm.sh/chart: {{ include "..chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-time-service
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.timeService.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "..name" . }}-time-service
      app.kubernetes.io/instance: {{ .Release.Name }}-time-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "..name" . }}-time-service
        app.kubernetes.io/instance: {{ .Release.Name }}-time-service
    spec:
      containers:
        - name: {{ .Chart.Name }}-time-service
          image: "{{ .Values.timeService.image.repository }}:{{ .Values.timeService.image.tag }}"
          imagePullPolicy: {{ .Values.timeService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-time-service-config-map
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
